import { Metadata } from "next";
import PortfolioPage from "../../page";
import { fetchUserData } from "../../portfolio";
import { toAbsoluteUrl } from "@/lib/site";
import { buildProjectPortfolioUrl } from "@/lib/server/withPortfolioContactLink";

type Props = {
  params: Promise<{ username: string; projectId: string }>;
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { username, projectId } = await params;

  // Fetch user data to find the project
  const { data, error } = await fetchUserData(username);

  if (error || !data || !data.projects) {
    // Fallback if data loading fails or user not found.
    // We let the layout metadata take over or provide a generic project title.
    // However, since we are deeper in the tree, we should return something.
    // If we return empty or partial, it merges.
    return {
      title: 'Project | PortfolioHub',
    };
  }

  const project = data.projects.projects.find((p) => p.id === projectId);

  if (!project) {
    return {
      title: 'Project Not Found | PortfolioHub',
    };
  }

  const title = `${project.title} | ${data.profile.full_name} | PortfolioHub`;
  const description = project.overview || `Check out ${project.title} by ${data.profile.full_name}`;

  const url =
    buildProjectPortfolioUrl(username, projectId) ||
    toAbsoluteUrl(`/${username}/project/${projectId}`);

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      url,
      type: 'article',
      // We do NOT set images here, so opengraph-image.tsx takes precedence
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      // Twitter card will also pick up og:image generated by opengraph-image.tsx
    },
  };
}

export default PortfolioPage;
